### ISSUE TITLE
Map error to exact solidity LOC

### ISSUE THREAD

**Issue by iShowCode** [melonproject/oyente#110]
when an error happens, I want to know the error happend in which function, can you give out this log???

**Comment by inian** [comment]
Hey,

Thank you for the report!

In case of an error, it is supposed to show the full stack trace. Can you share the contract you are trying it out on, so that we can debug?

**Comment by inian** [comment]
There was a particular program path where the stacktrace wasn't being printed. Have fixed it in this [commit](https://github.com/melonproject/oyente/commit/bcac7ac00da0a613fb0bf23b8652a41dbe82ebe5).

Could help check if this fixes your issue?

**Comment by iShowCode** [comment]
Hi,inian:
    Thanks for your answer, my test contract as follows: 
`contract KingOfTheEtherThrone {
    struct Monarch {
        // address of the king .
        address ethAddr ;
        string name ;
        // how much he pays to previous king
        uint claimPrice ;
        uint coronationTimestamp ;
    }
    address wizardAddress;
    Monarch public currentMonarch ;
    // claim the throne
    function claimThrone ( string name ) {
        if ( currentMonarch . ethAddr != wizardAddress )
            currentMonarch . ethAddr . send ( 100 );
    }
}`
by using oyente, i found a CallStack  Attack issue, like bellow:
`NFO:root:Contract KingOfTheEtherThrone.sol:KingOfTheEtherThrone:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  CallStack Attack: 	 True
INFO:symExec:	  Concurrency Bug: 	 False
INFO:symExec:	  Time Dependency: 	 False
INFO:symExec:	  Reentrancy bug exists: False
INFO:symExec:	====== Analysis Completed ======
`

beside this info , i want to know which function may cause this attack, of course,  for this example, the potential function is claimThrone. could your tool gives more log??? like
`INFO:symExec:	  CallStack Attack: 	 True       Location: clainThrone`

**Comment by inian** [comment]
Yup, that will be a very useful thing to have. Thing is oyente operates entirely on the disassembled opcodes. We lose information such as the function name, etc when we compile from solidity. Would be interesting to see if we can preserve relevant information when we compile down to opcodes so that we can pinpoint the exact location of the bug too.

**Comment by iShowCode** [comment]
thanks for your answer, and do you know some methods about how to preserve relevant information when we compile down to opcodes

**Comment by loiluu** [comment]
@inian `solc` has the feature to attach the  source code information to bytecode. Specificially, as mentioned by Yoichi, `solc/solc --asm-json foo.sol` associates each instruction with a range in the source code. 
For example,

```
{
                                        "begin" : 39,
                                        "end" : 43,
                                        "name" : "PUSH",
                                        "value" : "0"
},
```
means the PUSH comes from the source code characters 39--43 (counted from zero).

**Comment by iShowCode** [comment]
thanks for your direction, i have also found this command too.
