### ISSUE TITLE
Several instructions missing after evm disasm is called

### ISSUE THREAD

**Issue by leonardoalt** [melonproject/oyente#116]
Hi all,
I've been checking the following simple contract (trying to understand some of Oyente's internals):
```
pragma solidity ^0.4.0;
contract Test {
    uint32 x;
    function Test(uint32 y) {
        if(y > 9) x = y;
        else x = 7 * y;
    }
}
```
In oyente.py::analyze, when I print `disasm_out`, I get:
```
60606040525bfe00
000000: PUSH1 0x60
000002: PUSH1 0x40
000004: MSTORE
000005: JUMPDEST
000006: Missing opcode 0xfe
000007: STOP
```
As you can see, there are several things missing there.
Since I give a source file, Oyente will compile it using `solc` and then call `evm disasm`.

If I call `solc --optimize --bin-runtime --asm test.sol`, I get all the instructions, including the if/else jumps etc, therefore I assume that the bytecode generated without `--asm` will contain the same.
The issue comes when I call `evm disasm` on the bytecode. At this point most of the instructions simply vanish, hence the disasm that Oyente prints.

Does anybody have any idea what's the reason for that, and how to go around it?

Cheers,
Leo

**Comment by loiluu** [comment]
Hi Leo,

We encountered this problem before too. It is due to some disassambler bug that we reported [previously](https://github.com/ethereum/go-ethereum/issues/14376). Still waiting for their fix from the geth team.

**Comment by leonardoalt** [comment]
Oh I see. I was indeed wondering if it was a bug or a version thing.
Thanks for the quick reply! Let's hope we can get an update from them soon.
