### ISSUE TITLE
Results are not printed

### ISSUE THREAD

**Issue by leonardoalt** [melonproject/oyente#121]
Hi there,

After pulling the most recent code yesterday, the output that I get for a simple program is:
```
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  CallStack Attack: 	 False
INFO:symExec:	====== Analysis Completed ======
```

I've noticed that there is a new function `detect_bugs` that is called if the symbolic execution times out and prints the other results.
Why isn't it called if the symb exec goes through?

Cheers,
Leo

**Comment by luongnt95** [comment]
Thank Leo for reporting the issue. I've checked the code and fixed the issue. I forgot to keep the `dectect_bugs` after refactoring the code
