### ISSUE TITLE
Opcode EXTCODESIZE processing bug

### ISSUE THREAD

**Issue by exp10t** [melonproject/oyente#122]
Recently I am using Oyente to analyze smart contracts, and I think it is an excellent tool! 
However, I discover that there may exist a bug in symExec.py when it operates EXTCODESIZE. In the processing codes of this opcode, there is only one item should be poped out of stack. So in "if len(stack) > 1:", I think it should be: "if len(stack) > 0:".

When I ran some contract bytecode, Oyente usually 'STACK underflow'. For example this contract: 
0x2aFDf89A247305dAE5C77327681dF8923E40e5d1

So I think this is a bug. I don't know whether I am right or not?

**Comment by luongnt95** [comment]
You're right. I've fixed the bug.
