### ISSUE TITLE
Opcode "JUMP" and "JUMPI" processing bug

### ISSUE THREAD

**Issue by exp10t** [melonproject/oyente#123]
When it operates opcode "JUMP" and "JUMPI", it has conversion "target_address = int(str(simplify(target_address)))". In Python it may throw error: "ValueError: invalid literal for int() with base 10", when target_address is a string that contains non-number.

**Comment by loiluu** [comment]
Practically we don't think we can "jump" to a symbolic address since the code is static. Do you have any example where the target address is a symbolic value?

**Comment by luongnt95** [comment]
This line `target_address = int(str(simplify(target_address)))` is just for testing. In practice, I think we can't jump into a symbolic address as Loi mentioned.

**Comment by loiluu** [comment]
@luongnt95 Please consider using an assertion there!

**Comment by luongnt95** [comment]
[Here](https://github.com/melonproject/oyente/commit/d401a64c531476700eb7cc54ac94c3b8d21787a1) is my PR to handle exceptions in JUMP and JUMPI
