### ISSUE TITLE
Does not work with Solidity 0.4.12

### ISSUE THREAD

**Issue by SCBuergel** [melonproject/oyente#133]
When using any of the 0.4.12 compiler version and a corresponding `pragma solidity ^0.4.12;` I do not get any outputs regarding the checked issues, the result box is in fact empty:
<img width="710" alt="screen shot 2017-07-05 at 11 04 03" src="https://user-images.githubusercontent.com/11379673/27857381-c061cd54-6171-11e7-8ac5-e5d172806f48.png">

**Comment by luongnt95** [comment]
We are currently using solc version 0.4.11, so version 0.4.12 is not supported now. Will update the solc version and outputs the errors

**Comment by luongnt95** [comment]
@SCBuergel I've updated solidity compiler to the latest version, so now version 0.4.12 should work.
