### ISSUE TITLE
Opcodes failed

### ISSUE THREAD

**Issue by luongnt95** [melonproject/oyente#16]
Failed bitwise logic operation testcases: ['sgt3', 'lt1', 'slt2', 'not5', 'not1', 'not0', 'gt0']
=> Opcodes failed: SGT, LT, SLT, NOT, GT

**Comment by loiluu** [comment]
CC @inian. The test cases can be found in the json files within the tests folder.

**Comment by loiluu** [comment]
Hang on this first @inian. I think @luongnt95 just realized that some of the tests are actually false :)
