### ISSUE TITLE
"Reentrancy bug" given for send()

### ISSUE THREAD

**Issue by wanshun123** [melonproject/oyente#177]
Oyente will state there's a reentrancy bug on a line like `msg.sender.send(this.balance)`, however `send()` is safe from reentrancy attacks as it limits the gas to 2300 if transferring to another contract. I believe only `call()` is vulnerable to reentrancy (as stated in https://github.com/ConsenSys/smart-contract-best-practices#reentrancy)

**Comment by luongnt95** [comment]
@wanshun123 Can you provide me that contract so that I can debug. The tool is able to detect the case you said. You can find more details about what our tool can do with reentrancy bug [here](https://github.com/melonproject/oyente/blob/master/code.md) in the "reentracy bug" section

**Comment by luongnt95** [comment]
@wanshun123 Oh, the problem was caused because the solver failed to solve constraints. You can set the "timeout" to 1000 or greater instead of the default value which is 100 so that the solver can solve the constraints. I will add more information to the result to make the tool easier to use.
