### ISSUE TITLE
"solc" and "evm" commands not existing

### ISSUE THREAD

**Issue by wanshun123** [melonproject/oyente#182]
As described in https://ethereum.stackexchange.com/questions/26059/solc-and-evm-commands-not-existing I have geth and solcjs installed on my machine (and can run `geth` or `solcjs` anywhere - solcjs was installed via `npm install -g solc`) but they are not being picked up by Oyente - is there an easy workaround for this?

**Comment by luongnt95** [comment]
@wanshun123 Oyente uses `solc` instead of `solcjs`.

**Comment by luongnt95** [comment]
You can follow the instruction [here](https://github.com/melonproject/oyente) to install all needed dependencies
