### ISSUE TITLE
Cannot install Oyente on Mac after dependencies

### ISSUE THREAD

**Issue by designium** [melonproject/oyente#185]
Hi, 

I installed all the dependencies for oyente and it keeps giving me this error:

    $ pip install oyente
     Collecting oyente
      Using cached oyente-0.2.6.tar.gz
         Complete output from command python setup.py egg_info:
         Traceback (most recent call last):
           File "<string>", line 1, in <module>
           File "/private/var/folders/cl/vhg7nstx2gl895q4b88r0bv40000gn/T/pip-build-2dh8yavs/oyente/setup.py", line 10, in <module>
             long_description=open('README.md').read(),
        FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
        ----------------------------------------
     Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cl/vhg7nstx2gl895q4b88r0bv40000gn/T/pip-build-2dh8yavs/oyente/

**Comment by luongnt95** [comment]
@designium Can you please try using pip using python2 instead of python3 because our tool only works with python2
