### ISSUE TITLE
Call to ecrecover() flagged as callstack bug

### ISSUE THREAD

**Issue by mirathewhite** [melonproject/oyente#193]
I'm pretty sure this is a false positive. Otherwise, the call to keccak256 should generate the same error since both are precompiled contracts.

    function requireECDSASignatureFromValidSigner(
        bytes32 action, 
        bytes32 hashedTransaction, 
        bytes32 r, 
        bytes32 s, 
        uint8 v) private returns (address) 
    {
        bytes32 message = keccak256(action, hashedTransaction);
 
        bytes memory prefix = "\x19Ethereum Signed Message:\n32";
        bytes32 prefixedHash = keccak256(prefix, message);
        address signerAddress = ecrecover(
            prefixedHash,
            v,
            r,
            s
        );
        require(signerAddress != 0);
        require(isSigner[signerAddress]);
        return signerAddress;
    }

**Comment by luongnt95** [comment]
@mirathewhite Do you have a full contract so I can check. Do you run on docker or your local machine?

**Comment by mirathewhite** [comment]
I run oyente on my local machine (Mac). Here is a simple example that reproduces.  
<
pragma solidity ^0.4.14;

contract SimpleSig {

    // Users who are allowed to sign.
    mapping (address => bool) public isSigner;
    address[] signers;

    // Minimum required signatures
    uint public minSignaturesRequired = 2;

    // Maximum number of signers
    uint public maxSigners = 10;

    // Constructor
    function SimpleSig(address[] _signers) {
        require(minSignaturesRequired <= _signers.length);
        require(_signers.length <= maxSigners);

        // set signers, throw in case of duplicates
        for (uint i = 0; i < _signers.length; ++i) {
            require(! isSigner[_signers[i]]);
            isSigner[_signers[i]] = true;
        }
    }

    function checkSigs(
        bytes32 data, 
        bytes32[] rValues, 
        bytes32[] sValues, 
        uint8[] vValues ) returns (bool)
    {
        uint numSigs = rValues.length;

        require(numSigs == sValues.length);
        require(numSigs == vValues.length);
        require(numSigs <= signers.length);

        uint8 sigIndex;
        address approverAddress;

        // check if we received enough signatures
        require(numSigs >= minSignaturesRequired);

        // verify we got a valid and fresh APPROVE signature
        for (sigIndex = 0; sigIndex < numSigs; ++sigIndex) {
            approverAddress = requireECDSASignatureFromValidSigner(
                data,
                rValues[sigIndex], 
                sValues[sigIndex], 
                vValues[sigIndex]
            );
        }
        return true;
    }

    function requireECDSASignatureFromValidSigner(
        bytes32 data, 
        bytes32 r, 
        bytes32 s, 
        uint8 v) private constant returns (address) 
    {
        data = keccak256("\x19Ethereum Signed Message:\n32", data);
        address signerAddress = ecrecover(
            data,
            v,
            r,
            s
        );
        require(isSigner[signerAddress]);
        return signerAddress;
    }
}
>

**Comment by luongnt95** [comment]
Hi @mirathewhite It seems that you ran the old code base. Please pull the newest code and re-check it
