### ISSUE TITLE
Pip install issues

### ISSUE THREAD

**Issue by joeykrug** [melonproject/oyente#197]
`sudo pip install oyente` - All good
`oyente`
`No module named z3`

Tried
`sudo pip install z3`

Then

`oyente`

Get

`ImportError: No module named z3util`

**Comment by joeykrug** [comment]
Oh! Figured out the issue

need to also do `pip install z3-solver` --- this should be added as part of the pip install IMO

**Comment by luongnt95** [comment]
Thanks @joeykrug You could try using docker for the latest code

**Comment by domainexpert** [comment]
As I mentioned in #213, to resolve
```
ImportError: No module named z3util
```
on my system, I removed `from z3.z3util import ..` from `analysis.py` and `utils.py` and removed `import z3.z3util` from `oyente.py`.

**Comment by luongnt95** [comment]
@domainexpert Can you check z3 version on your system. Oyente runs z3 version 4.5.*

**Comment by domainexpert** [comment]
@luongnt95 The Z3 version is as follows:
```
$ z3 --version
Z3 version 4.5.1 - 64 bit
```

**Comment by joeykrug** [comment]
This works now
