### ISSUE TITLE
Handle loop better

### ISSUE THREAD

**Issue by loiluu** [melonproject/oyente#2]
_From @loiluu on September 21, 2016 4:59_

At the moment, Oyente terminates a path when seeing a loop, and proceeds to other ones. In other words, our SE only explores an under-approximation of all the program symbolic paths.

It might be useful to note that there is a technical challenge regarding loops: statically analysing bytecode will result in unbounded loops. E.g. Array copy from data input will result in a loop, and statically we don’t know the size of the data input.

_Copied from original issue: ethereum/oyente#2_

**Comment by loiluu** [comment]
A simple fix for this is to track how much gas has been spent and let the execution goes until the gas exceeds the [gas_limit](http://bitcoin.stackexchange.com/questions/39132/what-is-gas-limit-in-ethereum).

**Comment by inian** [comment]
Makes sense..We need to track the gas usage through the SE before we solve this issue then
