### ISSUE TITLE
incomplete results for outputing to json file

### ISSUE THREAD

**Issue by taxic** [melonproject/oyente#201]
All in symExec.py file:
In function run_callstack_attack(), detect_money_concurrency(), and detect_time_dependency(), there is no "results['**'] = bool(pcs)" in the last else branch.
Also, missing 'results["reentrancy"] = reentrancy_bug_found' in detect_reentrancy().

**Comment by luongnt95** [comment]
@taxic `results` is only used for the web version which requires the source code while the last else branch as you said is used for the binary

**Comment by taxic** [comment]
What about your results of running 'batch_run.py' on some contract*.json? 
My tmp.evm.disasm.json (results.json) contains neither 'true' nor 'false'.

**Comment by luongnt95** [comment]
My bad, `results` is also used in batch_run.py. The bug is fixed now anyway
