### ISSUE TITLE
Solidity import fails without information

### ISSUE THREAD

**Issue by AyushyaChitransh** [melonproject/oyente#204]
## Environment

The testing is being done on [online version](https://oyente.melon.network/#version=soljson-v0.4.17+commit.bdeb9e52.js) of oyente.

## Problem

Contracts having import statements do not compile. The reason for failure remains unknown. The "analyze" button gives `Solidity compilation failed` as the only output.

**Comment by luongnt95** [comment]
Thanks @AyushyaChitransh You can import files now on the web

**Comment by AyushyaChitransh** [comment]
It works now!
