### ISSUE TITLE
Opcode SLOAD doesn't handle enough case

### ISSUE THREAD

**Issue by luongnt95** [melonproject/oyente#21]
What happens if this condition occurs?
if isinstance(address, (int, long)) and address not in  global_state["Ia"]

**Comment by inian** [comment]
From [this page ](https://github.com/ethereum/wiki/wiki/Ethereum-Development-Tutorial), it looks like if there is nothing at that address, it should return 0.

**Comment by luongnt95** [comment]
Yes, I agree. So the fix should be a pull request.
