### ISSUE TITLE
Typo: “unkown”.

### ISSUE THREAD

**Issue by wlzla000** [melonproject/oyente#212]
`UNKOWN_INSTRUCTION` → `UNKNOWN_INSTRUCTION`

https://github.com/melonproject/oyente/blob/06c7ad1610283ce14cde1a1cb5da3306cc737018/oyente/symExec.py#L21

-----

`"Unkown instruction: %s"` → `"Unknown instruction: %s"`

https://github.com/melonproject/oyente/blob/06c7ad1610283ce14cde1a1cb5da3306cc737018/oyente/symExec.py#L1966

-----

`UNKOWN_INSTRUCTION` → `UNKNOWN_INSTRUCTION`

https://github.com/melonproject/oyente/blob/06c7ad1610283ce14cde1a1cb5da3306cc737018/oyente/symExec.py#L1967

**Comment by luongnt95** [comment]
Thanks @wlzla000 typo is corrected now
