### ISSUE TITLE
Opcode PUSH need to behave differently in range 1->32

### ISSUE THREAD

**Issue by luongnt95** [melonproject/oyente#22]
This is the code snippet that handle PUSH which behaves the same for all type of PUSH from PUSH1 -> PUSH32:
    elif instr_parts[0].startswith('PUSH', 0):  # this is a push instruction
        pushed_value = int(instr_parts[1], 16)
        stack.insert(0, pushed_value)

**Comment by inian** [comment]
I think the disassembler takes care of this. It reads the correct number of bytes and gives it as argument. 

1145   PUSH2  => 0002
...
1155   PUSH1  => 00

Once the correct number of bytes are read, the semantics of push1 to push 32 appear to be the same.

**Comment by loiluu** [comment]
Makes sense, so its not a bug then?
@luongnt95  can double check?

**Comment by inian** [comment]
Yup, I think not a bug. Please do double check though @luongnt95
