### ISSUE TITLE
Typo: `detect_vulnerabilies`.

### ISSUE THREAD

**Issue by wlzla000** [melonproject/oyente#228]
`detect_vulnerabilies` → `detect_vulnerabilities`.

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2211

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2357

**Comment by luongnt95** [comment]
Thanks @wlzla000 .
