### ISSUE TITLE
failed to compile when there a call to other contract

### ISSUE THREAD

**Issue by karnawat83** [melonproject/oyente#233]
Below are the sample of two contract:

pragma solidity ^0.4.8;
    contract A {
       function testA() constant returns(uint d) {
           return 5;
       }
    }

 pragma solidity ^0.4.8;

import "./A.sol";

    contract B {
       function testB() constant returns(uint d) {
           return new A().testA();

       }
    }

**Comment by luongnt95** [comment]
@karnawat83 you ran these contracts in docker, local machine or the web?
