### ISSUE TITLE
debug mode is showing error when contract referes to constant values

### ISSUE THREAD

**Issue by karnawat83** [melonproject/oyente#234]
Following are the sample contracts

File: c.sol
pragma solidity ^0.4.8;
contract C{
    mapping(bytes32 => uint) UIntStorage;
    function getUIntValue(bytes32 record) constant returns (uint){
        return UIntStorage[record];
    }

    function setUIntValue(bytes32 record, uint value)    {
        UIntStorage[record] = value;
    }
}

File: lib.sol
pragma solidity ^0.4.8;
import "./C.sol";
library lib { 
    string constant index   = "index";
    function getA(address store) constant returns(uint d) {
      return C(store).getUIntValue(sha3(index));
   }
       
  function setA(address store) {
       C(store).setUIntValue(sha3(index), 1);
    }
}

File: A.sol
pragma solidity ^0.4.8;
import "./lib.sol";
contract A {
      address public store;
     using lib for address;       
     string constant index   = "index";       
     function A(){
        store = new C();
      }
       
   function getA() constant returns(uint d) {
          return store.getA();
   }       
   function setA()  {
       store.setA();
    }
}

Output attached here
![output](https://user-images.githubusercontent.com/30497750/33021360-99adcf14-ce27-11e7-89f8-bbc0ccfd4364.png)

**Comment by karnawat83** [comment]
if we execute without -db parameter, due to these background error code coverage percentage was low.

**Comment by luongnt95** [comment]
@karnawat83 You have to increase -t and -glt option til these exceptions disappear then the code coverage percentage might be higher.
