### ISSUE TITLE
Failed to compile if documentation description missing for param

### ISSUE THREAD

**Issue by karnawat83** [melonproject/oyente#235]
Following contract to failed to compile because documentation comments parameter missing description of the parameter. 

Sample Contract

pragma solidity ^0.4.8;
contract C{
    mapping(bytes32 => uint) UIntStorage;
    /**
     * function to get value of the spcecied record
     * @param record 
     * @return val   
     */
    function getUIntValue(bytes32 record) constant returns (uint val){
        return UIntStorage[record];
    }

    /**
     * 
     * function to set value for the record
     * @param record 
     * @param value  
     */
    function setUIntValue(bytes32 record, uint value)
    {
        UIntStorage[record] = value;
    }   
}
![output](https://user-images.githubusercontent.com/30497750/33024304-bb109d22-ce30-11e7-8a2f-6a06b20f997a.png)

**Comment by luongnt95** [comment]
@karnawat83 This error is expected. Oyente can't run if the contract is not compiled
