### ISSUE TITLE
check for evm version with hard coded values

### ISSUE THREAD

**Issue by karnawat83** [melonproject/oyente#236]
While running oyente with docker container, docker file is downloading ethereum Version as 1.7.1. while running oyente,we are gettting following warning :-1: 
  WARNING:root:You are using evm version 1.7.1. The supported version is 1.6.6

Reason: check for evm version with hard code value : 1.6.6 in oyente.py file.

**Comment by luongnt95** [comment]
@karnawat83 I think it's normal to check for evm version with a hard code value in this case.
