### ISSUE TITLE
Getting consistently low EVM code coverage results

### ISSUE THREAD

**Issue by postables** [melonproject/oyente#241]
For Whatever reason when using the command line utility I can't get high code coverage results. I'm consistently getting low percentages, varying from 2% to 10%.

When using the web app version I was able to increase code coverage results by upping the gas limits, depth limits and so on but doing that with the command line utility seems to have no effect

**Comment by luongnt95** [comment]
@postables The result also relies heavily on your local machine's hardware. If the hardware is weak then you have to increase -t option and -glt option to be able to get higher percentage

**Comment by postables** [comment]
@luongnt95  
I'm running it off an i7-4790K overclocked to 4.7GHz,
I also have a 24  threaded Xeon processor that I can try later on today to see if i can bump up the code coverage percentage.

I also tried last night manipulating -t, -glt, and -ll but could not get my code coverage higher.

**Comment by luongnt95** [comment]
@postables Let try `python oyente.py -s test.sol --debug -t 1000` and see if there's any exception raised like this: `Z3Exception: canceled`. You need to increase -t option til this exception disappears

**Comment by postables** [comment]
@luongnt95  I was able to get it to stop complaining about timeouts with the following parameters:
`--debug -t 10000000000000000000000000000 -glt 2000000000`

Unfortunately due to CPU constraints it is taking my workstation much to long so I'm considering spinning up a dedicated EC2 instance to run oyente on.

Python is single-threaded unless programs are configured to take advantage of multi-threaded/parallel processing. Is oyente setup to take advantage of multiple cores/processors?

**Comment by luongnt95** [comment]
@postables nice. We haven't had any plan on that.

**Comment by vietlq** [comment]
The current design of Oyente uses so much of global variables that makes it difficult to maintain and scale (run in multiple-threads). I raised an issue about refactoring that can help to launch multiple-threads after removing all global variables:

https://github.com/melonproject/oyente/issues/309
