### ISSUE TITLE
SELFDESTRUCT opcode should replace SUICIDE

### ISSUE THREAD

**Issue by MKong** [melonproject/oyente#242]
Since EIP6, the `SUICIDE` op code has been replaced by `SELFDESRUCT`. This should be replaced in all instances of `SUICIDE`, for example, in the `calculate_gas` function.

**Comment by luongnt95** [comment]
@MKong Because SELFDESTRUCT is added as an alias of SUICIDE opcode (rather than replacing it), we convert all SELFDESTRUCT to SUICIDE opcode before running Oyente. I think this shouldn't be a problem.
