### ISSUE TITLE
what is EVM code coverage?

### ISSUE THREAD

**Issue by dominictarr** [melonproject/oyente#252]
I read the oyente paper, then installed and ran the oyente tool, and in the output I saw "EVM code coverage"
looking at lots of contracts, sometimes it would say "100%" but often smaller than 50% or even 0.

I didn't see anything in the documentation or paper about coverage. Searching the code I found this:
``` py
 evm_code_coverage = float(len(visited_pcs)) / len(instructions.keys()) * 100
```
https://github.com/melonproject/oyente/blob/b3cdac8898a06ba4518907e6f0cf922f74b25469/oyente/symExec.py#L2212

how should I interpret this when looking at results? I would assume that getting 100% is good, and that 0% means this contract isn't one that is possible for onyente to analyze?

**Comment by luongnt95** [comment]
evm_code_coverage = number of opcodes executed / total number of opcodes. To increase the code coverage you can try increasing -t option. Could you run Oyente with the contracts that results in 0% of evm code coverage with --debug flag and provide me the screenshot of it?
