### ISSUE TITLE
Timestamp dependency detection

### ISSUE THREAD

**Issue by Telluur** [melonproject/oyente#258]
Does the detection for timestamp dependency still work? 
The contract used as example in the paper http://www.comp.nus.edu.sg/~loiluu/papers/oyente.pdf does not yield a positive flag for timestamp dependency.
Neither does this simple contract:

```
contract Gamble {
    uint privSeed;
    uint pot;

    function bet() public payable {
        pot += msg.value;
        
        //generate bad pseudorand
        privSeed = (privSeed*3 + 1) / 2;
        privSeed = privSeed % 10**9;
        uint rand = (privSeed + block.timestamp) % 37;

        if (rand > 100) {
            msg.sender.transfer(pot);
        }
    }
}

```

Mythril (https://github.com/ConsenSys/mythril) does report a timestamp dependency. 

Using Oyente version 0.2.7 pulled from pip, haven't checked the paper's version of Oyente (https://github.com/melonproject/oyente/tree/290f1ae1bbb295b8e61cbf0eed93dbde6f287e69).

**Comment by luongnt95** [comment]
Hey @Telluur . This condition `if (rand > 100)` is unsatisfied because `rand < 37`

**Comment by Telluur** [comment]
My apologies, I tried minimalising the code example for this report without completely thinking it through. 

If you change the condition `rand > 100` to `rand < 20`  or remove ` % 37` , then `msg.sender.transfer(pot);` should be executable, correct? And if my understanding is correct, the `transfer()` call is dependent on the timestamp.

Oyente does not flag either of those changes as vulnerable

**Comment by subhramazumdar** [comment]
Hi @luongnt95 I tried the method mentioned by you but it is till not working
