### ISSUE TITLE
SLOAD potential error

### ISSUE THREAD

**Issue by xuanbachle** [melonproject/oyente#259]
SLOAD in oyente when executing with the below solidity code, will have new_var_name as "return greeting", which I think it makes more sense to be "greeting" instead.
==========================
contract mortal {
    /* Define variable owner of the type address */
    address owner;

    /* This function is executed at initialization and sets the owner of the contract */
    function mortal() { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() { if (msg.sender == owner) selfdestruct(owner); }
}

contract greeter is mortal {
    /* Define variable greeting of the type string */
    string greeting;
    int a = 5;
    /* This runs when the contract is executed */
    function greeter(string _greeting) public {
        greeting = _greeting;
    }

    /* Main function */
    function greet() constant returns (string) {
        return greeting;
    }
}
============================

**Comment by xuanbachle** [comment]
Oyente seems to run fine with the code above. But if I make the code to change from: "return greeting;" change to "return (a line break here)
                             greeting;" then Oyente does not recognize greeting as a state variable anymore. The code at SLOAD and for identifying parameter or state variable look rather extremely adhoc and not systematic ...

**Comment by luongnt95** [comment]
Thanks. The bug is fixed now. [This] (https://github.com/melonproject/oyente/commit/eabaa82a9d612f37c158875f3b46c080909b5ae8) is the commit
