### ISSUE TITLE
Feature request: Consider also the contracts created by other contracts 

### ISSUE THREAD

**Issue by tina1998612** [melonproject/oyente#260]
When I tried evaluating my smart contracts with the remix integration with Oyente, I noticed that Oyente did not discover that one of my contracts (say contract A) is only to be created by other contracts instead of normal addresses. An assertion failure is thus raised for the modifier `onlyContractCreator` since Oyente created contract A by a normal address.

Any help or suggestions are welcomed. Thanks!!

**Comment by luongnt95** [comment]
@tina1998612 Could you provide me a sample contract that causes the above problem?
