### ISSUE TITLE
Exit code of oyente is not consistent

### ISSUE THREAD

**Issue by lpassos** [melonproject/oyente#265]
Oyente returns a non-zero exit code even when it successfully finishes execution.

**Comment by lazzarello** [comment]
Hey Leo, can you provide some more detail about this issue? Perhaps some example output to reproduce?

**Comment by lpassos** [comment]
@lazzarello If you submit a file to `oyente` (e.g., save https://github.com/quantstamp/smart-contract-security-database/blob/4054e01366ca56e1645431ff4b0f133566060da1/dao-bug/oyente-paper-example-fig-7.sol as /tmp/input.sol), call it as 

```
oyente.py -j -s input.sol ; echo $?
```

you will see that `echo $?` outputs 1, which in POSIX systems is an error code. However, `oyente` did run successfully, reporting an accurate vulnerability.

**Comment by luongnt95** [comment]
@lpassos Oyente will return 1 if it finds any vulnerability. Otherwise, it will return 0
