### ISSUE TITLE
Doesn't work with latest solc 0.4.19 and evm 1.6.7 versions

### ISSUE THREAD

**Issue by chapati23** [melonproject/oyente#268]
<img width="652" alt="screen shot 2018-02-08 at 11 41 06" src="https://user-images.githubusercontent.com/117495/35968732-fa14435c-0cc4-11e8-9826-24506027ecff.png">

**Comment by lazzarello** [comment]
have you tried the latest release?

```
solc --version
solc, the solidity compiler commandline interface
Version: 0.4.21+commit.dfe3193c.Linux.g++
```

**Comment by chapati23** [comment]
sry, we since migrated to mythril, closing this one…
