### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by fccbb** [melonproject/oyente#277]
% oyente --version                                                  
oyente version 0.2.7 - Commonwealth

when I run oyente I get this :

```shell

% oyente -ru https://github.com/phenom-company/ico-smartcontract-appics/blob/master/contracts/ICO.sol
WARNING:root:You are using an untested version of z3. 4.5.0 is the officially tested version
WARNING:root:You are using evm version 1.8.2. The supported version is 1.6.6
WARNING:root:You are using solc version 0.4.21, The latest supported version is 0.4.17
Traceback (most recent call last):
  File "/usr/sbin/oyente", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/oyente/oyente.py", line 208, in main
    f.write(code)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 1107: ordinal not in range(128)
```

It's the same message in Docker. Any input would be very appreciated

**Comment by fccbb** [comment]
my locales are set UTF-8

```shell
% locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE=en_GB.UTF-8
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

**Comment by lazzarello** [comment]
#278 was merged. try the latest `master` branch.

**Comment by OneCoin5759** [comment]
Could you put thd master branch images to https://hub.docker.com

**Comment by OneCoin5759** [comment]
@luongnt95 thanks

**Comment by OneCoin5759** [comment]
@luongnt95 ![image](https://user-images.githubusercontent.com/12327646/37452566-ec0e0cfe-286f-11e8-9640-7612bdb1eaba.png)

**Comment by luongnt95** [comment]
@fccbb @OneCoin5759 The url must direct to a raw solidity file instead of a HTML file. eg: `https://raw.githubusercontent.com/phenom-company/ico-smartcontract-appics/master/contracts/ICO.sol` instead of `https://github.com/phenom-company/ico-smartcontract-appics/blob/master/contracts/ICO.sol
`. And you should pull the docker image again.
