### ISSUE TITLE
ModuleNotFoundError: No module named 'symExec'

### ISSUE THREAD

**Issue by fccbb** [melonproject/oyente#290]
sorry mistake delete this

**Comment by vietlq** [comment]
I got the same error when trying to run on macOS:

```
ModuleNotFoundError: No module named 'symExec'
```

**Comment by luongnt95** [comment]
@vietlq It's appreciated if you could make a PR for this. I don't have macOS installed so not sure what goes wrong

**Comment by vietlq** [comment]
@luongnt95 sure :)

**Comment by srisankethu** [comment]
@luongnt95 This issue was not complete. When doing ``sudo python3 setup.py install`` results in this error. Fixed this error in #347 .
