### ISSUE TITLE
Integration : Oyente tool launch on iExec

### ISSUE THREAD

**Issue by branciard** [melonproject/oyente#304]
Hi Oyente Team,

We have successfully test your oyente docker image to be to be launch on iExec. So, smart contracts analyses can we launch on remotes workers.

See here for the test : https://github.com/iExecBlockchainComputing/iexec-dapps-registry/tree/oyenteTest

Are you ok to be listed in this dapps store ? : 
https://dapps.iex.ec/

If so, if you have a Oyente logo to provide you can sent it to me.

Thanks,

Francois

**Comment by retotrinkler** [comment]
Hi @branciard 

Yes ofc.

Logos are here https://github.com/melonproject/branding/tree/master/oyente
eg:
https://github.com/melonproject/branding/blob/master/oyente/04_oyente_logo_transparent.png
https://github.com/melonproject/branding/blob/master/oyente/03_oyente_logo.jpg

KR

**Comment by branciard** [comment]
Thanks. it now added in https://dapps.iex.ec/dapp/oyente
