### ISSUE TITLE
PEP8: Use flake8 & yapf for readable & beautiful Python code

### ISSUE THREAD

**Issue by vietlq** [melonproject/oyente#310]
I'm happy to help with this one. The tools are located at:

https://github.com/PyCQA/flake8

https://github.com/google/yapf

**Comment by luongnt95** [comment]
Awesome!

**Comment by vietlq** [comment]
@luongnt95 Great, I will create PR for that :)

**Comment by vietlq** [comment]
There are lots of style errors detected by Flake8:

https://travis-ci.org/vietlq/oyente/jobs/371942593

**Comment by yxliang01** [comment]
Since #320 has been merged, is this issue still relevant? @vietlq

**Comment by vietlq** [comment]
This can be closed
