### ISSUE TITLE
bytecode evaluation

### ISSUE THREAD

**Issue by arun-munagala** [melonproject/oyente#324]
How can i input just the bytecode of a contract?
i tried  "python oyente.py -s example.bytecode -b"
but it returns with the following error:
WARNING:root:You are using evm version 1.8.6. The supported version is 1.7.3
WARNING:root:You are using solc version 0.4.23, The latest supported version is 0.4.19
encoding/hex: invalid byte: U+0078 'x'
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 0/0
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Money concurrency bug: False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
Traceback (most recent call last):
  File "oyente.py", line 221, in <module>
    main()
  File "oyente.py", line 210, in main
    exit_code = analyze_bytecode()
  File "oyente.py", line 72, in analyze_bytecode
    result, exit_code = symExec.run(disasm_file=inp['disasm_file'])
  File "/home/iam/oyente/oyente/symExec.py", line 2458, in run
    ret = detect_vulnerabilities()
  File "/home/iam/oyente/oyente/symExec.py", line 2315, in detect_vulnerabilities
    return results, vulnerability_found()
  File "/home/iam/oyente/oyente/symExec.py", line 2346, in vulnerability_found
    vulnerabilities = [callstack, money_concurrency, time_dependency, reentrancy]
NameError: global name 'callstack' is not defined

**Comment by luongnt95** [comment]
It seems that you're using the old code. You should pull the latest code or use docker instead.

**Comment by arun-munagala** [comment]
Thank you for the reply. I did a pull but i get the same error. There are no issues when i run url example or do it on a source code contract. 
Is there any particular format or type of file the bytecode should be in? 
I just copied the bytecode from etherscan and pasted in a text file locally and used the above command. Did i do something wrong here?

**Comment by arun-munagala** [comment]
p.s. i am yet to try in docker. but wanted to know if it runs like this

**Comment by arun-munagala** [comment]
Just more information. the example.bytecode file contains this:
'0x606060405260e060020a600035046369425ebe8114601a575b005b60186001544210603f5760005473ffffffffffffffffffffffffffffffffffffffff16ff5b600256'
Some random bytecode found in etherscan.io

**Comment by luongnt95** [comment]
You should remove the prefix '0x'

**Comment by arun-munagala** [comment]
Ah okay! thank you.

**Comment by 77aq** [comment]
It works for some contracts. But  some bytecodes still report the error after remove the prefix '0x'. 
I did not use docker.
The example.bytecode files are :

[YAMBYO.txt](https://github.com/melonproject/oyente/files/2213085/YAMBYO.txt)
[YES.txt](https://github.com/melonproject/oyente/files/2213078/YES.txt)
