### ISSUE TITLE
Can oyente inspect contracts in one path?

### ISSUE THREAD

**Issue by GuminTom** [melonproject/oyente#325]
A contract may include many solidity files, how oyente inspect the contract?
Besides , we hope oyente can inspect multiple contracts at once too.

**Comment by luongnt95** [comment]
If a contract includes many solidity files, Oyente will also inspect contracts in these files. 

> Besides , we hope oyente can inspect multiple contracts at once too.
Do you want Oyente to run with multiple contracts which are not related to each other?
