### ISSUE TITLE
Running benchmark gives ValueError

### ISSUE THREAD

**Issue by inian** [melonproject/oyente#33]
Running batch_run.py gives this error in a lot of cases. Is this a regression?

```
ERROR:root:Storage key or value is not a number
Traceback (most recent call last):
  File "symExec.py", line 94, in compare_storage_unit_test
    key = str(long(key))
ValueError: invalid literal for long() with base 10: 'some_var_3'
```

**Comment by inian** [comment]
confirmed to be a regression

**Comment by luongnt95** [comment]
I have to check that

**Comment by luongnt95** [comment]
You need to set UNIT_TEST = 0 to skip the storage test because the test can't work with opcodes that doesn't handle real values

**Comment by loiluu** [comment]
@inian can you please update the status of this issue?

**Comment by inian** [comment]
yup setting UNIT_TEST=0 seems to remove the errors i was getting
