### ISSUE TITLE
Status of oyente project

### ISSUE THREAD

**Issue by yxliang01** [melonproject/oyente#352]
Hello members of Oyente project, I(we) would like to know the status of this Oyente project now. E.g. discontinued, low-priority, etc... I'm asking this because there are many open issues and one PR that don't have any comment from your team. I think it would be better if the status of this project can be known by the community.

Thanks for making Oyente!

CC: @luongnt95 @loiluu

**Comment by loiluu** [comment]
Hey @yxliang01 I believe @luongnt95 is currently maintaining it, though he may have other higher priority concerns. We at Kyber Network team are looking for a couple of people to actively maintain Oyente, if you are interested and have relevant background, please let us know.

**Comment by yxliang01** [comment]
@loiluu Thanks for your info. As I'm planning to make use of Oyente as of now, I might fix bugs when they eventually prevent me from using it. However, I'm afraid that I don't have much time for really maintaining this. But, if you need to, I'm happy to help review pull requests and answer questions in the repo if I'm available.

**Comment by yxliang01** [comment]
Okay I think the status of Oyente is clear to me now. Thanks @loiluu
