### ISSUE TITLE
Exception:Source map error

### ISSUE THREAD

**Issue by Xcrab** [melonproject/oyente#360]
If the contract is normal,this tool can  works fine,but when the contract have some security bugs(like the Puzzle in the paper),it always tell me "Source map error",why?

![screenshot from 2018-10-30 21-56-53](https://user-images.githubusercontent.com/20314873/47723902-7ae48c80-dc90-11e8-8a8a-3b7cc7a1500f.png)

**Comment by yxliang01** [comment]
Are you using the compatible compiler and evm? @Xcrab

**Comment by Xcrab** [comment]
> Are you using the compatible compiler and evm? @Xcrab

I use evm version 1.8.17 and solc version 0.4.25,Must be use evm version 1.7.3 and solc 0.4.19?

**Comment by Xcrab** [comment]
> Are you using the compatible compiler and evm? @Xcrab

I use evm version 1.8.17 and solc version 0.4.25,Must be use evm version 1.7.3 and solc 0.4.19?

**Comment by yxliang01** [comment]
I am not sure. But I suspect that the source map functionality might not be compatible with the newer versions. Would you like to try degrading and see whether it works for the same setup and input?

**Comment by Xcrab** [comment]
> I am not sure. But I suspect that the source map functionality might not be compatible with the newer versions. Would you like to try degrading and see whether it works for the same setup and input?

I try degrading and it work！！！Thanks for your suggestion.(I use evm version 1.7.3 and solc 0.4.25)

**Comment by yxliang01** [comment]
Welcome. So, again, this is related to issues like https://github.com/melonproject/oyente/issues/346 and many others. Hope the Oyente team can make it support the newer versions. @luongnt95 I think you are the only maintainer now. Is there any plan to do this?

**Comment by yxliang01** [comment]
Well, you could have used the `Dockerfile` to build a docker image. In this way, you don't need to downgrade. But, don't use the docker image built by @luongnt95 at the moment. Since it will still have this problem until @luongnt95 rebuilds on the code base after the PR https://github.com/melonproject/oyente/pull/341 and push to dockerhub.

**Comment by daanwa** [comment]
Any news if newer versions of evm and solc are going to be supported?

**Comment by yxliang01** [comment]
@daanwa I truly hope there will be... but I don't know.. The develop team doesn't look active..

**Comment by chenhan0027** [comment]
hi, how to downgrade the version of evm and sold? @Xcrab

**Comment by matYang** [comment]
Any plans to support Solidity 0.5+ ? I finally got the right evm and solc in docker to work with oyente, but getting a consistent source map error on sol 0.5+ contracts.

**Comment by enderphan94** [comment]
> > I am not sure. But I suspect that the source map functionality might not be compatible with the newer versions. Would you like to try degrading and see whether it works for the same setup and input?
> 
> I try degrading and it work！！！Thanks for your suggestion.(I use evm version 1.7.3 and solc 0.4.25)

How could you downgrade the evm version? Thanks so much

**Comment by yxliang01** [comment]
@enderphan94 : you can downgrade the evm version by installing an old version of `evm`, or you can just build oyente from the latest version of dockerfile which has the right version of `solc` and `evm` configured.

@matYang : If you can file an issue with the reproducing information, I can look into it.

Closing this issue as the problem has been resolved.
