### ISSUE TITLE
Error while building image from dockerfile

### ISSUE THREAD

**Issue by anhdungle93** [melonproject/oyente#388]
Hi, first I tried to run docker with the image from README.md file but got error with solc and evm version. I then noticed that this issue has been solved and updated in the dockerfile but still not reflected in the docker image, so I decided to build the image from dockerfile myself, but I got the following error.

```
Step 32/34 : RUN ./bin/yarn install && gem install bundler && bundle install --with development
 ---> Running in 62462e4b6dc9
mesg: ttyname failed: Inappropriate ioctl for device
/bin/bash: ./bin/yarn: No such file or directory
The command '/bin/bash -c -l ./bin/yarn install && gem install bundler && bundle install --with development' returned a non-zero code: 127
```

**Comment by yxliang01** [comment]
Hi @anhdungle93 , may I quickly know whether you need the Web UI for Oyente? Or is CLI sufficient?

**Comment by anhdungle93** [comment]
Hi, @yxliang01 just CLI is enough, thanks.

**Comment by yxliang01** [comment]
@anhdungle93  I see. I will look into it later. Potentially, I can do #387 to skip this bug for now. TBH, I feel the Web component might be ok to be deprecated since I haven't really seen people using it and maintaining it looks quite some efforts required.

**Comment by yxliang01** [comment]
@anhdungle93 I have follow this up in #389 .

**Comment by yxliang01** [comment]
@anhdungle93 FYI, from the conversion with you in #389, I think there is no issue in building the WEB component. It was a problem with your previous setup.
