### ISSUE TITLE
Solidity compilation failed

### ISSUE THREAD

**Issue by lukwue** [melonproject/oyente#391]
Hello,

Oyente can't compile Solidity code even though it is the same file as in Oyentes README.

```
(env) user@user-VirtualBox:~/analyzer/env/lib/python2.7/site-packages/oyente$ python oyente.py -s test.sol
WARNING:root:You are using an untested version of z3. 4.5.0 is the officially tested version
WARNING:root:You are using evm version 1.9.13. The supported version is 1.6.6
WARNING:root:You are using solc version 0.6.7, The latest supported version is 0.4.17
CRITICAL:root:Solidity compilation failed
======= error =======
Solidity compilation failed


```
Somehow, Oyente also doesn't seem to recognize the right Z3 version (even though it is installed). Could this have something to do with the compile error?
```
(env) user@user-VirtualBox:~/analyzer/env/lib/python2.7/site-packages/oyente$ z3 --version
Z3 version 4.5.0 - 64 bit
```

**Comment by yxliang01** [comment]
I'm a bit confused. From the log, it looks like it is the contract that failed to compile, instead of problem of z3?

**Comment by lukwue** [comment]
> 
> 
> I'm a bit confused. From the log, it looks like it is the contract that failed to compile, instead of problem of z3?

Sorry, yes the problem is it can't compile Solidity code. I thought it might have something to do with the mysterious fact that it can't recognize the correct Z3 version.

**Comment by yxliang01** [comment]
@lukwue can you try to see whether there's syntax error in your contract or Solidity version mismatch? If it's not an issue of Oyente, we can close this.

**Comment by lukwue** [comment]
I used the URL from one of the examples in the Oyente readme file so the contract should be correct.

**Comment by yxliang01** [comment]
I realized that you are not using the officially supported `solc` version. Would you like to use the supported version instead? Or, do you want to convert this to a feature request to support `solc` 0.6?

**Comment by lukwue** [comment]
Ok, thank you very much.
I also needed to use the supported `evm ` version. 
It is really confusing though that the instructions in the README-file install evm and solc versions which are not supported. Do you think I should file a request for a change of the README-files?
Btw: When I compile a solidity file to evm byte code with the newest evm version and then test the byte code with Oyente, should it work?

**Comment by yxliang01** [comment]
It's true that the instruction would lead to installation of the latest version. A PR to improve the clarity would be welcome!

For new evm version, I think the best way is to try and error. In case of any problem, we can always create an issue to discuss and fix.

**Comment by lukwue** [comment]
Ok, thank you.
