### ISSUE TITLE
how to target a specified contract in a solidity file

### ISSUE THREAD

**Issue by Qiana0223** [melonproject/oyente#397]
Hi developer!

I have simple question. Suppose I want to analyze one target contract in a solidity file which contains multiple contracts, what command I should provide, or to be specific what flag I should include?

I do appreciate your help!

**Comment by yxliang01** [comment]
Hi @Qiana0223 , currently this master branch code doesn't have such functionality. I have implemented back then, but it's not merged to this codebase. If you wish, I can try to port it over here in next few days. However, as I don't have an environment to allow me to test, I will need your help on the testing if I do so. Alternatively, we can wait until I have got an environment, but it might take weeks. Let me know what you think :)

**Comment by Qiana0223** [comment]
Would you please port it in one or two days? I will definitely help on testing. Thanks!

**Comment by yxliang01** [comment]
I'm busy there two days. I will try to get to it on Thur. @Qiana0223

**Comment by Qiana0223** [comment]
ok, thank you!

**Comment by yxliang01** [comment]
@Qiana0223 PR #398 has been made to add this missing feature.

**Comment by Qiana0223** [comment]
Hi @yxliang01 
I have tested it with 10 files.
Here, I show one example: HoloToken.sol, which has two contracts.
**python oyente.py -s HoloToken.sol**
![image](https://user-images.githubusercontent.com/32651102/83197186-b52f3d80-a102-11ea-9610-84f5248c0f05.png)

**python oyente.py --target-contracts HoloToken HoloToken.sol**
![image](https://user-images.githubusercontent.com/32651102/83197215-c2e4c300-a102-11ea-89be-7b19890c1755.png)

So,  oyente has the feature of analyzing specified contract.

**Comment by yxliang01** [comment]
@Qiana0223 Thank you for testing! If you have any further issues, please let me know!

**Comment by Qiana0223** [comment]
Thank you!
