### ISSUE TITLE
https://oyente.melonport.com

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/oyente#67]
hosted node for rpc calls to get latest blockchain data

**Comment by loiluu** [comment]
@retotrinkler when can we expect the node to be ready?

**Comment by retotrinkler** [comment]
@loiluu will be up in <24hrs; just about to board plane

**Comment by retotrinkler** [comment]
ok server should be up

sample call
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://oyente.melonport.com
```

sample response

```
{"jsonrpc":"2.0","result":"0x370888","id":1}
```
